//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XM_Tek_Studio_Pro.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XM_Tek_Studio_Pro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ######################################
        ///
        ///# IC / Version : Command Mode
        ///# Panel : AUO 5.5&quot; H546DAN09
        ///# Initial code version : V03
        ///# Release date : 2019/11/21
        ///# History : modify timing setting
        ///#           modify enmode   
        ///
        ///######################################
        ///
        ///#XM91080 FPGA Setting                                                                                
        ///fpga.set 0x01 0x11 0x07 0x00 0 0
        ///mipi.video 1920 1080 0 0 0 0 0 0 0 
        ///mipi.dsi 4 800 burst
        ///
        ///bridge.read 0xb0 2
        ///
        ///                      [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _008_Command_mode_init_code {
            get {
                return ResourceManager.GetString("_008_Command_mode_init_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _30_Office_48x48 {
            get {
                object obj = ResourceManager.GetObject("_30_Office_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap about_us {
            get {
                object obj = ResourceManager.GetObject("about-us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap agilent_logo_76x64 {
            get {
                object obj = ResourceManager.GetObject("agilent_logo_76x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Aglient {
            get {
                object obj = ResourceManager.GetObject("Aglient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CA210 {
            get {
                object obj = ResourceManager.GetObject("CA210", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CA210_NO {
            get {
                object obj = ResourceManager.GetObject("CA210_NO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CA210_Open {
            get {
                object obj = ResourceManager.GetObject("CA210_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap center_sp {
            get {
                object obj = ResourceManager.GetObject("center_sp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap centerl {
            get {
                object obj = ResourceManager.GetObject("centerl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ciexyz {
            get {
                object obj = ResourceManager.GetObject("ciexyz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CLOSE_MSG {
            get {
                return ResourceManager.GetString("CLOSE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap closeall {
            get {
                object obj = ResourceManager.GetObject("closeall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap closeBlack {
            get {
                object obj = ResourceManager.GetObject("closeBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Comm 的本地化字符串。
        /// </summary>
        internal static string COMM_MSG {
            get {
                return ResourceManager.GetString("COMM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command,Class,Type,Category,MaxValue,MaxParm,Reg,Delay,Least,Item,,
        ///id,3,2,0,0,1,,,,,,
        ///fpga.set,3,1,3,255,7,,,,,,
        ///fpga.write,3,1,10,255,6,,,,,,
        ///fpga.read,3,0,3,255,3,,,,,,
        ///bridge.select,3,1,3,17,2,,,,,,
        ///bridge.write,3,1,9,255,4,,,,,,
        ///bridge.read,3,0,3,255,3,,,,,,
        ///gpio.dir,3,1,3,255,2,fa,,,,,
        ///gpio.write,3,1,9,255,3,,,,,,
        ///gpio.set,3,1,9,255,3,fb,,,,,
        ///gpio.h.set,3,1,9,255,3,fb,,,,,
        ///gpio.l.set,3,1,9,255,3,fc,,,,,
        ///gpio.read,3,0,3,255,1,,,,,,
        ///gpio.clr,3,1,9,255,1,,,,,,
        ///mipi.dsi,3,1,5,4096,4,,,,sync [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Command_List {
            get {
                return ResourceManager.GetString("Command_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CommClose {
            get {
                object obj = ResourceManager.GetObject("CommClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CommConfig {
            get {
                object obj = ResourceManager.GetObject("CommConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Comment {
            get {
                object obj = ResourceManager.GetObject("Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CommOpen {
            get {
                object obj = ResourceManager.GetObject("CommOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CommPlay {
            get {
                object obj = ResourceManager.GetObject("CommPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 #Script CPT4.7 iPhone 6 initial code 20180521
        ///####################
        ///fpga.set 0x33 0x11 0x13 0xff 67 60            #PLL_EN ; EPP_EN ; I/F_mode1 ; I/F_mode2 ; DCM_m ; DCM_d
        ///bridge.select 0x01                                #Bridge select 0x01=Bank0(Left) 0x10=Bank2(Right)
        ///mipi.video 1334 750 60 16 16 30 30 4 4           #VA ; HA ; FR ; VBP ; VFP ; HBP ; HFP ; VS ; HS
        ///mipi.dsi 3 850 burst                              #Lane Num ; HS speed ; HS mode
        ///
        ///bridge.write 0xc9 0x1c 0x07                     # data1: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CPT47_iPhone6_initialcode_20180521 {
            get {
                return ResourceManager.GetString("CPT47_iPhone6_initialcode_20180521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus {
            get {
                object obj = ResourceManager.GetObject("cpu data bus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus_1 {
            get {
                object obj = ResourceManager.GetObject("cpu data bus_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus_2 {
            get {
                object obj = ResourceManager.GetObject("cpu data bus_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus_3 {
            get {
                object obj = ResourceManager.GetObject("cpu data bus_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus_4 {
            get {
                object obj = ResourceManager.GetObject("cpu data bus_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus_5 {
            get {
                object obj = ResourceManager.GetObject("cpu data bus_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus_6 {
            get {
                object obj = ResourceManager.GetObject("cpu data bus_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus_7 {
            get {
                object obj = ResourceManager.GetObject("cpu data bus_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cpu_data_bus_8 {
            get {
                object obj = ResourceManager.GetObject("cpu data bus_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Cut1_0_Item_1_1_Power {
            get {
                object obj = ResourceManager.GetObject("Cut1_0_Item_1_1_Power", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap de_p0 {
            get {
                object obj = ResourceManager.GetObject("de_p0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap de_p1 {
            get {
                object obj = ResourceManager.GetObject("de_p1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [System]
        ///ScriptDir=NULL
        ///
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string Default_Config_V01 {
            get {
                return ResourceManager.GetString("Default_Config_V01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap del {
            get {
                object obj = ResourceManager.GetObject("del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap digital {
            get {
                object obj = ResourceManager.GetObject("digital", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap display {
            get {
                object obj = ResourceManager.GetObject("display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap empty_72x72 {
            get {
                object obj = ResourceManager.GetObject("empty_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] EPP2USB_DLL_V12 {
            get {
                object obj = ResourceManager.GetObject("EPP2USB_DLL_V12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap exit_64x64 {
            get {
                object obj = ResourceManager.GetObject("exit_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap flash {
            get {
                object obj = ResourceManager.GetObject("flash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap hs_p0 {
            get {
                object obj = ResourceManager.GetObject("hs_p0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap hs_p1 {
            get {
                object obj = ResourceManager.GetObject("hs_p1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap i2c_timing {
            get {
                object obj = ResourceManager.GetObject("i2c_timing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_stop_trans {
            get {
                object obj = ResourceManager.GetObject("icon_stop_trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IfSet {
            get {
                object obj = ResourceManager.GetObject("IfSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] INRUSH_CURRENT_RIPPLE_RELAY_BOARD_UserGuide {
            get {
                object obj = ResourceManager.GetObject("INRUSH_CURRENT_RIPPLE_RELAY_BOARD_UserGuide", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap K80 {
            get {
                object obj = ResourceManager.GetObject("K80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] KClmtrWrapper {
            get {
                object obj = ResourceManager.GetObject("KClmtrWrapper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 CPU , I80 的本地化字符串。
        /// </summary>
        internal static string LOG_CPU_I80 {
            get {
                return ResourceManager.GetString("LOG_CPU_I80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU , M68 的本地化字符串。
        /// </summary>
        internal static string LOG_CPU_M68 {
            get {
                return ResourceManager.GetString("LOG_CPU_M68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo_i2c {
            get {
                object obj = ResourceManager.GetObject("logo_i2c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 COMMENT 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_COMMENT {
            get {
                return ResourceManager.GetString("MSG_SPT_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR(No Cmd , Par Err) 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_ERR {
            get {
                return ResourceManager.GetString("MSG_SPT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 for and endfor must be Paired 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_FORERR {
            get {
                return ResourceManager.GetString("MSG_SPT_FORERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is short of endfor 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_LACKENDFOR {
            get {
                return ResourceManager.GetString("MSG_SPT_LACKENDFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is short of for 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_LACKFOR {
            get {
                return ResourceManager.GetString("MSG_SPT_LACKFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PASS 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_PASS {
            get {
                return ResourceManager.GetString("MSG_SPT_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 READMSG 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_READ {
            get {
                return ResourceManager.GetString("MSG_SPT_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SPACE 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_SPACE {
            get {
                return ResourceManager.GetString("MSG_SPT_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARN(Parm&gt;255) 的本地化字符串。
        /// </summary>
        internal static string MSG_SPT_WARN {
            get {
                return ResourceManager.GetString("MSG_SPT_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap newtab {
            get {
                object obj = ResourceManager.GetObject("newtab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap open_32 {
            get {
                object obj = ResourceManager.GetObject("open_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap open_48 {
            get {
                object obj = ResourceManager.GetObject("open_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string OPEN_MSG {
            get {
                return ResourceManager.GetString("OPEN_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CA-210 / K8 的本地化字符串。
        /// </summary>
        internal static string OPTICS_MSG {
            get {
                return ResourceManager.GetString("OPTICS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap oscilloscope {
            get {
                object obj = ResourceManager.GetObject("oscilloscope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap oscilloscope_s {
            get {
                object obj = ResourceManager.GetObject("oscilloscope_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap oscilloscope1 {
            get {
                object obj = ResourceManager.GetObject("oscilloscope1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] PAT_gen_V13 {
            get {
                object obj = ResourceManager.GetObject("PAT_gen_V13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Pattern {
            get {
                object obj = ResourceManager.GetObject("Pattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pclk_p0 {
            get {
                object obj = ResourceManager.GetObject("pclk_p0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pclk_p1 {
            get {
                object obj = ResourceManager.GetObject("pclk_p1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap play_green_64x64 {
            get {
                object obj = ResourceManager.GetObject("play_green_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PWM {
            get {
                object obj = ResourceManager.GetObject("PWM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PWM_Icon {
            get {
                object obj = ResourceManager.GetObject("PWM-Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_chart {
            get {
                object obj = ResourceManager.GetObject("RGB chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_d000 {
            get {
                object obj = ResourceManager.GetObject("RGB_d000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_d001 {
            get {
                object obj = ResourceManager.GetObject("RGB_d001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_d010 {
            get {
                object obj = ResourceManager.GetObject("RGB_d010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_d011 {
            get {
                object obj = ResourceManager.GetObject("RGB_d011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_d100 {
            get {
                object obj = ResourceManager.GetObject("RGB_d100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_d101 {
            get {
                object obj = ResourceManager.GetObject("RGB_d101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_d110 {
            get {
                object obj = ResourceManager.GetObject("RGB_d110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_d111 {
            get {
                object obj = ResourceManager.GetObject("RGB_d111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_DATA_BUS {
            get {
                object obj = ResourceManager.GetObject("RGB DATA BUS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RGB_DATA_BUS1 {
            get {
                object obj = ResourceManager.GetObject("RGB DATA BUS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Right_Arrow_48x48 {
            get {
                object obj = ResourceManager.GetObject("Right_Arrow_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RS232 {
            get {
                object obj = ResourceManager.GetObject("RS232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RS232_NO {
            get {
                object obj = ResourceManager.GetObject("RS232_NO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RS232_Open {
            get {
                object obj = ResourceManager.GetObject("RS232_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Save_48x48 {
            get {
                object obj = ResourceManager.GetObject("Save_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SDCardtoBin {
            get {
                object obj = ResourceManager.GetObject("SDCardtoBin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon slew {
            get {
                object obj = ResourceManager.GetObject("slew", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap slew_icon {
            get {
                object obj = ResourceManager.GetObject("slew_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap source {
            get {
                object obj = ResourceManager.GetObject("source", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_3w9b {
            get {
                object obj = ResourceManager.GetObject("spi_3w9b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_4w8b {
            get {
                object obj = ResourceManager.GetObject("spi_4w8b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_csbymodule {
            get {
                object obj = ResourceManager.GetObject("spi_csbymodule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_csbyuser {
            get {
                object obj = ResourceManager.GetObject("spi_csbyuser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_fet {
            get {
                object obj = ResourceManager.GetObject("spi_fet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_rd_wdmy {
            get {
                object obj = ResourceManager.GetObject("spi_rd_wdmy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_rd_wodmy {
            get {
                object obj = ResourceManager.GetObject("spi_rd_wodmy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_ret {
            get {
                object obj = ResourceManager.GetObject("spi_ret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap spi_sck_speed {
            get {
                object obj = ResourceManager.GetObject("spi_sck_speed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stop_red_64x64 {
            get {
                object obj = ResourceManager.GetObject("stop_red_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 I80 的本地化字符串。
        /// </summary>
        internal static string STR_CPU_I80 {
            get {
                return ResourceManager.GetString("STR_CPU_I80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M68 的本地化字符串。
        /// </summary>
        internal static string STR_CPU_M68 {
            get {
                return ResourceManager.GetString("STR_CPU_M68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU 的本地化字符串。
        /// </summary>
        internal static string STR_CPU_MSG {
            get {
                return ResourceManager.GetString("STR_CPU_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fpga.set 0x00 0x00 的本地化字符串。
        /// </summary>
        internal static string STR_FPGA_SET {
            get {
                return ResourceManager.GetString("STR_FPGA_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I2C 的本地化字符串。
        /// </summary>
        internal static string STR_I2C {
            get {
                return ResourceManager.GetString("STR_I2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 i2c.set 的本地化字符串。
        /// </summary>
        internal static string STR_I2C_SET {
            get {
                return ResourceManager.GetString("STR_I2C_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x00 0x00 的本地化字符串。
        /// </summary>
        internal static string STR_NULL_HEX {
            get {
                return ResourceManager.GetString("STR_NULL_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SPI 的本地化字符串。
        /// </summary>
        internal static string STR_SPI {
            get {
                return ResourceManager.GetString("STR_SPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 spi.set 的本地化字符串。
        /// </summary>
        internal static string STR_SPI_SET {
            get {
                return ResourceManager.GetString("STR_SPI_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully 的本地化字符串。
        /// </summary>
        internal static string SUCCESS_MSG {
            get {
                return ResourceManager.GetString("SUCCESS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap temp {
            get {
                object obj = ResourceManager.GetObject("temp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnComment {
            get {
                object obj = ResourceManager.GetObject("UnComment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap USB_Icon {
            get {
                object obj = ResourceManager.GetObject("USB_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap vs_p0 {
            get {
                object obj = ResourceManager.GetObject("vs_p0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap vs_p1 {
            get {
                object obj = ResourceManager.GetObject("vs_p1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ;------------------------------------------------------------
        ///; Xm+_USB20.INF  --   Windows 8/7/2000/9x/Me Setup File 
        ///;
        ///; For Xm-plus USB controller
        ///;------------------------------------------------------------
        ///[Version]
        ///Signature=&quot;$CHICAGO$&quot;
        ///Provider=&quot;Xiamen Xm-plus Technology Ltd.&quot;
        ///LayoutFile=layout.inf, layout1.inf, layout2.inf
        ///DriverVer = 04/10/2013,2.0.4
        ///Class=Xm-plus
        ///ClassGUID={46D426C2-048D-4DB7-A198-D6814E24B341}
        ///
        ///; ================= Class section =====================
        ///[ClassInstall]        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Xm_USB20_v11 {
            get {
                return ResourceManager.GetString("Xm_USB20_v11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [GAMMA]
        ///NODE=0,1,3,5,7,9,11,13,15,23,31,47,63,95,127,128,160,192,208,224,232,240,242,244,246,248,250,252,254,255
        ///Bright=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///R+=1,2,22,54,96,127,147,164,180,236,273,331,375,442,501,503,564,646,694,765,805,852,867,883,899,919,943,970,1004,1023
        ///R-=1,2,22,54,9 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Xm92180 {
            get {
                return ResourceManager.GetString("Xm92180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] XMColoredLib {
            get {
                object obj = ResourceManager.GetObject("XMColoredLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] XMGridViewCtrl {
            get {
                object obj = ResourceManager.GetObject("XMGridViewCtrl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap XmMain {
            get {
                object obj = ResourceManager.GetObject("XmMain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap XmPlus {
            get {
                object obj = ResourceManager.GetObject("XmPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
